/**
 * Build identifier — used by the "New version available" pill to detect
 * when a fresh deploy has shipped while a tab is open.
 *
 * The committed value (`'dev'`) is what runs in local development.
 * The real production SHA is written into this file by
 * `.github/workflows/deploy.yml` immediately before `gcloud run deploy`,
 * so the Cloud Build container picks up the right value at build time.
 *
 * DO NOT edit this file by hand for production — it'll be overwritten.
 * (Use a comment-only change like this one when you need to bump the
 * deployed SHA for a smoke test of the update-available pill.)
 */

// Annotated as `string` (not the literal) so TypeScript doesn't narrow the
// type. Otherwise the production-baked SHA in this file would make the
// `BUILD_ID === 'dev'` runtime guard a type error ("no overlap").
export const BUILD_ID: string = 'dev';
export const BUILT_AT: string = '';
