/**
 * Build identifier — used by the "New version available" pill to detect
 * when a fresh deploy has shipped while a tab is open.
 *
 * The committed value (`'dev'`) is what runs in local development.
 * The real production SHA is written into this file by
 * `.github/workflows/deploy.yml` immediately before `gcloud run deploy`,
 * so the Cloud Build container picks up the right value at build time.
 *
 * DO NOT edit this file by hand for production — it'll be overwritten.
 */

export const BUILD_ID = 'dev';
export const BUILT_AT = '';
